/**
 * Sanity Studio Seed Data — Baig Tours Pakistan
 *
 * This file contains all demo content for testing the CMS.
 * Import these objects into Sanity Studio manually or via a script.
 *
 * Usage (manual):
 *   1. Open /studio in your browser
 *   2. Create documents matching each schema
 *   3. Paste the content from the relevant export
 *
 * Usage (script):
 *   npm install sanity
 *   npx sanity dataset import seed.json production
 */

// ─── CATEGORIES ──────────────────────────────────────────

export const categories = [
  {
    _type: "category",
    _id: "category-adventure",
    name: "Adventure",
    slug: { current: "adventure" },
    icon: "Mountain",
    description: "Jeep safaris, glaciers & high passes",
    order: 1,
  },
  {
    _type: "category",
    _id: "category-trekking",
    name: "Trekking",
    slug: { current: "trekking" },
    icon: "Footprints",
    description: "Base camps & multi-day trails",
    order: 2,
  },
  {
    _type: "category",
    _id: "category-luxury",
    name: "Luxury",
    slug: { current: "luxury" },
    icon: "Gem",
    description: "Boutique stays & private guides",
    order: 3,
  },
  {
    _type: "category",
    _id: "category-family",
    name: "Family",
    slug: { current: "family" },
    icon: "Users",
    description: "Easy-paced, kid-friendly itineraries",
    order: 4,
  },
  {
    _type: "category",
    _id: "category-culture",
    name: "Culture",
    slug: { current: "culture" },
    icon: "Landmark",
    description: "Heritage cities & living history",
    order: 5,
  },
  {
    _type: "category",
    _id: "category-honeymoon",
    name: "Honeymoon",
    slug: { current: "honeymoon" },
    icon: "Heart",
    description: "Romantic escapes for two",
    order: 6,
  },
];

// ─── DESTINATIONS ──────────────────────────────────────────

export const destinations = [
  {
    _type: "destination",
    _id: "dest-hunza",
    name: "Hunza Valley",
    slug: { current: "hunza" },
    region: "Gilgit-Baltistan",
    province: "Gilgit-Baltistan",
    description: "Terraced orchards, snow-capped Rakaposhi and the warmth of Hunzai hospitality make this the crown jewel of Northern Pakistan.",
    bestTime: "April – October",
    coordinates: { x: 58, y: 12 },
    order: 1,
  },
  {
    _type: "destination",
    _id: "dest-skardu",
    name: "Skardu",
    slug: { current: "skardu" },
    region: "Gilgit-Baltistan",
    province: "Gilgit-Baltistan",
    description: "Gateway to the Karakoram giants — cold deserts, turquoise lakes and the road to K2 all begin here.",
    bestTime: "May – September",
    coordinates: { x: 68, y: 18 },
    order: 2,
  },
  {
    _type: "destination",
    _id: "dest-fairy-meadows",
    name: "Fairy Meadows",
    slug: { current: "fairy-meadows" },
    region: "Gilgit-Baltistan",
    province: "Gilgit-Baltistan",
    description: "A pine-fringed meadow facing Nanga Parbat, reachable only by jeep track and a short forest trek.",
    bestTime: "June – September",
    coordinates: { x: 50, y: 20 },
    order: 3,
  },
  {
    _type: "destination",
    _id: "dest-swat",
    name: "Swat Valley",
    slug: { current: "swat-valley" },
    region: "Khyber Pakhtunkhwa",
    province: "Khyber Pakhtunkhwa",
    description: "Known as the Switzerland of Pakistan — green slopes, river valleys and family-friendly resorts.",
    bestTime: "March – November",
    coordinates: { x: 38, y: 24 },
    order: 4,
  },
  {
    _type: "destination",
    _id: "dest-naran",
    name: "Naran & Kaghan",
    slug: { current: "naran-kaghan" },
    region: "Khyber Pakhtunkhwa",
    province: "Khyber Pakhtunkhwa",
    description: "Home to Lake Saif-ul-Malook and a string of alpine lakes threaded along the Kunhar river.",
    bestTime: "May – September",
    coordinates: { x: 42, y: 28 },
    order: 5,
  },
  {
    _type: "destination",
    _id: "dest-lahore",
    name: "Lahore",
    slug: { current: "lahore" },
    region: "Punjab",
    province: "Punjab",
    description: "Mughal grandeur, walled-city food streets and Pakistan's cultural heartbeat.",
    bestTime: "October – March",
    coordinates: { x: 60, y: 62 },
    order: 6,
  },
  {
    _type: "destination",
    _id: "dest-murree",
    name: "Murree",
    slug: { current: "murree" },
    region: "Punjab",
    province: "Punjab",
    description: "A colonial hill station an hour from the capital — pine forests, mist and cable cars.",
    bestTime: "March – August, December (snow)",
    coordinates: { x: 46, y: 40 },
    order: 7,
  },
  {
    _type: "destination",
    _id: "dest-concordia",
    name: "Concordia & K2",
    slug: { current: "concordia" },
    region: "Gilgit-Baltistan",
    province: "Gilgit-Baltistan",
    description: "The ultimate trekking prize: four 8,000m giants ringing a single glacial amphitheatre.",
    bestTime: "June – August",
    coordinates: { x: 72, y: 10 },
    order: 8,
  },
];

// ─── TOUR PACKAGES ──────────────────────────────────────────

export const tourPackages = [
  {
    _type: "tourPackage",
    _id: "tour-hunza-luxury",
    title: "Hunza Valley Luxury Escape",
    slug: { current: "hunza-valley-luxury-escape" },
    tag: "Most Loved",
    destination: { _type: "reference", _ref: "dest-hunza" },
    category: { _type: "reference", _ref: "category-luxury" },
    region: "Gilgit-Baltistan",
    description: "A curated luxury journey through Hunza's golden orchards, turquoise lakes and ancient forts — with boutique stays and private guides at every step.",
    highlights: [
      "Sunrise over Rakaposhi from a private balcony suite",
      "Guided walk through Karimabad's old town and Baltit Fort",
      "Private boat ride on the turquoise Attabad Lake",
      "Apricot orchard breakfast with a local Hunzai family",
    ],
    price: 89500,
    originalPrice: 104000,
    duration: "6 Days / 5 Nights",
    nights: 5,
    groupSize: "2–12 people",
    difficulty: "Easy",
    included: [
      "5-night boutique hotel stay",
      "Private air-conditioned vehicle & driver",
      "Daily breakfast and 3 curated dinners",
      "English-speaking mountain guide",
      "All entry fees & permits",
    ],
    excluded: ["International/domestic airfare", "Travel insurance", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Arrival in Gilgit → Hunza", description: "Scenic drive along the Karakoram Highway, evening arrival in Karimabad with a welcome dinner overlooking the valley." },
      { day: 2, title: "Baltit & Altit Forts", description: "Full day exploring centuries-old forts, traditional Hunzai villages and terraced orchards." },
      { day: 3, title: "Attabad Lake & Passu Cones", description: "Private boat ride on Attabad Lake followed by golden-hour photography at the Passu Cathedral peaks." },
      { day: 4, title: "Eagle's Nest Sunrise", description: "Early departure to Duikar viewpoint for sunrise over Rakaposhi, free afternoon for leisure." },
      { day: 5, title: "Khunjerab Valley Day Trip", description: "Optional drive toward the China border region, wildlife spotting in Khunjerab National Park." },
      { day: 6, title: "Departure", description: "Leisurely breakfast, souvenir shopping in Karimabad bazaar, transfer to Gilgit airport." },
    ],
    rating: 4.9,
    reviewCount: 214,
    bookedCount: 1840,
    featured: true,
    bestSeller: true,
    order: 1,
  },
  {
    _type: "tourPackage",
    _id: "tour-skardu-adventure",
    title: "Skardu Adventure Expedition",
    slug: { current: "skardu-adventure-expedition" },
    tag: "Adventure",
    destination: { _type: "reference", _ref: "dest-skardu" },
    category: { _type: "reference", _ref: "category-adventure" },
    region: "Gilgit-Baltistan",
    description: "An adrenaline-fueled expedition through Skardu's cold desert, Deosai plains and turquoise alpine lakes — the adventure capital of Pakistan.",
    highlights: [
      "Jeep safari across the Cold Desert dunes of Skardu",
      "Trek to the base of Deosai's Sheosar Lake",
      "Sunset at Shangrila Resort's Lower Kachura Lake",
      "Camping night under the clearest skies in Pakistan",
    ],
    price: 76000,
    duration: "5 Days / 4 Nights",
    nights: 4,
    groupSize: "4–16 people",
    difficulty: "Moderate",
    included: ["4-night stay (hotel + camping)", "4x4 jeep transport", "All meals", "Certified trek guide", "Camping equipment"],
    excluded: ["Airfare to Skardu", "Personal gear", "Travel insurance"],
    itinerary: [
      { day: 1, title: "Arrival & Cold Desert", description: "Land in Skardu, jeep ride across the Katpana Cold Desert dunes." },
      { day: 2, title: "Deosai National Plains", description: "Drive to Deosai, spot Himalayan brown bears, overnight camping." },
      { day: 3, title: "Sheosar Lake Trek", description: "Morning trek to Sheosar Lake, return to Skardu by evening." },
      { day: 4, title: "Shangrila & Upper Kachura", description: "Boating and photography at two of Pakistan's most photographed lakes." },
      { day: 5, title: "Departure", description: "Free morning, transfer to airport." },
    ],
    rating: 4.8,
    reviewCount: 176,
    bookedCount: 1320,
    featured: true,
    order: 2,
  },
  {
    _type: "tourPackage",
    _id: "tour-fairy-meadows",
    title: "Fairy Meadows & Nanga Parbat Base Camp Trek",
    slug: { current: "fairy-meadows-nanga-parbat-trek" },
    tag: "Trekking",
    destination: { _type: "reference", _ref: "dest-fairy-meadows" },
    category: { _type: "reference", _ref: "category-trekking" },
    region: "Gilgit-Baltistan",
    description: "Trek to the foot of the Killer Mountain through one of the world's most thrilling jeep tracks and alpine meadows.",
    highlights: [
      "Jeep ride up one of the world's most thrilling mountain tracks",
      "Trek to Nanga Parbat Base Camp, the Killer Mountain",
      "Wooden cabin stay beneath pine forests",
      "Unobstructed views of the ninth-highest peak on Earth",
    ],
    price: 62500,
    duration: "4 Days / 3 Nights",
    nights: 3,
    groupSize: "6–14 people",
    difficulty: "Challenging",
    included: ["3-night cabin stay", "Jeep transfer from Raikot Bridge", "All meals", "Local trekking guide & porter"],
    excluded: ["Transport to Raikot Bridge", "Sleeping bags", "Travel insurance"],
    itinerary: [
      { day: 1, title: "Raikot Bridge → Fairy Meadows", description: "Thrilling jeep ascent followed by a short forest trek to the meadows." },
      { day: 2, title: "Base Camp Trek", description: "Full-day trek to Nanga Parbat Base Camp with packed lunch." },
      { day: 3, title: "Leisure & Viewpoints", description: "Relaxed day exploring Bayal Camp viewpoint and pine forest trails." },
      { day: 4, title: "Descent & Departure", description: "Morning descent to Raikot Bridge, onward transfer." },
    ],
    rating: 4.7,
    reviewCount: 141,
    bookedCount: 980,
    order: 3,
  },
  {
    _type: "tourPackage",
    _id: "tour-swat-family",
    title: "Swat, Kalam & Malam Jabba Family Tour",
    slug: { current: "swat-kalam-malam-jabba-family-tour" },
    tag: "Family Favorite",
    destination: { _type: "reference", _ref: "dest-swat" },
    category: { _type: "reference", _ref: "category-family" },
    region: "Khyber Pakhtunkhwa",
    description: "A relaxed family adventure through Pakistan's Switzerland — chairlifts over pine slopes, river picnics and ancient Buddhist ruins.",
    highlights: [
      "Chairlift ride over the pine slopes of Malam Jabba",
      "River-side picnic in Kalam's green valley",
      "Visit to the ancient Buddhist ruins of Butkara",
      "Family-friendly hotel with playground & river view",
    ],
    price: 54000,
    duration: "5 Days / 4 Nights",
    nights: 4,
    groupSize: "2–20 people",
    difficulty: "Easy",
    included: ["4-night family rooms", "Private van with driver", "Daily breakfast & dinner", "Chairlift tickets"],
    excluded: ["Lunch", "Travel insurance", "Personal shopping"],
    itinerary: [
      { day: 1, title: "Islamabad → Mingora", description: "Scenic drive into Swat, check-in and evening at leisure." },
      { day: 2, title: "Malam Jabba", description: "Chairlift rides, mountain zipline and alpine walks." },
      { day: 3, title: "Kalam Valley", description: "River picnic, visit Mahodand-adjacent viewpoints." },
      { day: 4, title: "Marghazar & Fizagat Park", description: "White Palace visit and family time at Fizagat Park." },
      { day: 5, title: "Departure", description: "Morning at leisure, drive back to Islamabad." },
    ],
    rating: 4.8,
    reviewCount: 268,
    bookedCount: 2210,
    featured: true,
    bestSeller: true,
    order: 4,
  },
  {
    _type: "tourPackage",
    _id: "tour-naran-kaghan",
    title: "Naran, Kaghan & Saif-ul-Malook Tour",
    slug: { current: "naran-kaghan-saif-ul-malook-tour" },
    tag: "Best Value",
    destination: { _type: "reference", _ref: "dest-naran" },
    category: { _type: "reference", _ref: "category-adventure" },
    region: "Khyber Pakhtunkhwa",
    description: "Discover the legendary Lake Saif-ul-Malook, horse trails along the Kaghan river and alpine meadows at 3,400 metres.",
    highlights: [
      "Jeep ride to the legendary Lake Saif-ul-Malook",
      "Horse ride along the Kaghan river trails",
      "Visit Lulusar Lake at 3,410 metres",
      "Bonfire evening with live regional music",
    ],
    price: 48000,
    duration: "4 Days / 3 Nights",
    nights: 3,
    groupSize: "2–16 people",
    difficulty: "Easy",
    included: ["3-night hotel stay", "4x4 jeep to Saif-ul-Malook", "Daily breakfast", "Bonfire & dinner night"],
    excluded: ["Lunch", "Horse ride fees", "Travel insurance"],
    itinerary: [
      { day: 1, title: "Arrival in Naran", description: "Check-in, evening riverside walk and welcome bonfire." },
      { day: 2, title: "Saif-ul-Malook & Lulusar", description: "Full day covering both alpine lakes." },
      { day: 3, title: "Shogran & Siri Paye", description: "Chairlift and meadow walk with Makra Peak views." },
      { day: 4, title: "Departure", description: "Breakfast and drive back." },
    ],
    rating: 4.6,
    reviewCount: 302,
    bookedCount: 2670,
    order: 5,
  },
  {
    _type: "tourPackage",
    _id: "tour-lahore-heritage",
    title: "Lahore Heritage & Culinary City Tour",
    slug: { current: "lahore-heritage-culinary-city-tour" },
    tag: "City Break",
    destination: { _type: "reference", _ref: "dest-lahore" },
    category: { _type: "reference", _ref: "category-culture" },
    region: "Punjab",
    description: "Walk the royal trail of Mughal Lahore, taste the city's legendary street food and witness the Wagah Border ceremony.",
    highlights: [
      "Badshahi Mosque and Lahore Fort guided walk",
      "Wagah Border flag-lowering ceremony",
      "Food trail through the walking streets of Old Anarkali",
      "Evening at the illuminated Delhi Gate",
    ],
    price: 28500,
    duration: "3 Days / 2 Nights",
    nights: 2,
    groupSize: "2–25 people",
    difficulty: "Easy",
    included: ["2-night 4-star hotel", "Private city guide", "Wagah Border transfer", "Food trail with 6 tastings"],
    excluded: ["Flights", "Lunch on day 2", "Travel insurance"],
    itinerary: [
      { day: 1, title: "Old City Walking Tour", description: "Lahore Fort, Badshahi Mosque and the Royal Trail." },
      { day: 2, title: "Wagah Border & Food Trail", description: "Afternoon border ceremony followed by an Old Anarkali food walk." },
      { day: 3, title: "Departure", description: "Shalimar Gardens visit and onward transfer." },
    ],
    rating: 4.9,
    reviewCount: 189,
    bookedCount: 1560,
    order: 6,
  },
  {
    _type: "tourPackage",
    _id: "tour-k2-basecamp",
    title: "K2 Base Camp & Concordia Trek",
    slug: { current: "k2-basecamp-concordia-trek" },
    tag: "Expedition",
    destination: { _type: "reference", _ref: "dest-concordia" },
    category: { _type: "reference", _ref: "category-trekking" },
    region: "Gilgit-Baltistan",
    description: "The ultimate trekking expedition to the throne room of the world's highest peaks — a 14-day journey through Baltoro Glacier to Concordia.",
    highlights: [
      "Stand at Concordia, the throne room of four 8,000m peaks",
      "Trek past Baltoro Glacier, one of the largest outside the poles",
      "Full expedition support with high-altitude porters",
      "Certificate of completion from Baig Tours Expeditions",
    ],
    price: 245000,
    duration: "14 Days / 13 Nights",
    nights: 13,
    groupSize: "6–10 people",
    difficulty: "Expert",
    included: ["Full expedition logistics", "All camping & meals on trek", "Government-licensed HAP guides", "Permits & park fees"],
    excluded: ["Flights to Islamabad/Skardu", "Personal trekking gear", "Emergency evacuation insurance"],
    itinerary: [
      { day: 1, title: "Islamabad → Skardu", description: "Flight or scenic drive to Skardu, briefing and gear check." },
      { day: 2, title: "Skardu → Askole", description: "Jeep transfer to the last village before the wilderness." },
      { day: 3, title: "Trek to Jhola", description: "First trekking day along the Braldu river." },
      { day: 4, title: "Jhola → Paiju", description: "Approach to the snout of Baltoro Glacier." },
      { day: 5, title: "Rest Day at Paiju", description: "Acclimatization and gear preparation." },
      { day: 6, title: "Paiju → Khoburtse", description: "Onto the glacier proper." },
      { day: 7, title: "Khoburtse → Concordia", description: "Arrival at Concordia beneath K2, Broad Peak and Gasherbrums." },
      { day: 8, title: "Concordia Exploration", description: "Optional push to K2 Base Camp." },
      { day: 9, title: "Return Trek Begins", description: "Retrace to Khoburtse." },
      { day: 10, title: "Khoburtse → Paiju", description: "Continued descent." },
      { day: 11, title: "Paiju → Jhola", description: "Descent along the Baltoro." },
      { day: 12, title: "Jhola → Askole", description: "Final trekking day." },
      { day: 13, title: "Askole → Skardu", description: "Jeep transfer back to Skardu." },
      { day: 14, title: "Departure", description: "Flight/drive back to Islamabad." },
    ],
    rating: 5.0,
    reviewCount: 58,
    bookedCount: 210,
    order: 7,
  },
  {
    _type: "tourPackage",
    _id: "tour-murree-honeymoon",
    title: "Islamabad & Murree Honeymoon Getaway",
    slug: { current: "islamabad-murree-honeymoon-getaway" },
    tag: "Romantic",
    destination: { _type: "reference", _ref: "dest-murree" },
    category: { _type: "reference", _ref: "category-honeymoon" },
    region: "Punjab",
    description: "A romantic escape through the capital's landmarks and Murree's misty pine forests — candlelight dinners, couples' spa and sunset chairlifts.",
    highlights: [
      "Private candlelight dinner overlooking the Pindi valley",
      "Couples' spa evening at a boutique pine-forest resort",
      "Sunset chairlift at Patriata (New Murree)",
      "Guided Faisal Mosque & Daman-e-Koh photo session",
    ],
    price: 68000,
    duration: "4 Days / 3 Nights",
    nights: 3,
    groupSize: "2 people",
    difficulty: "Easy",
    included: ["3-night couple suite", "Private candlelight dinner", "Couples spa session", "Private car with driver"],
    excluded: ["Flights", "Lunch", "Travel insurance"],
    itinerary: [
      { day: 1, title: "Arrival in Islamabad", description: "Faisal Mosque and Daman-e-Koh sunset viewpoint." },
      { day: 2, title: "Murree Mall Road", description: "Leisurely walk, cable car, evening candlelight dinner." },
      { day: 3, title: "Patriata New Murree", description: "Chairlift and cable car ride, couples spa in the evening." },
      { day: 4, title: "Departure", description: "Morning at leisure, transfer to airport." },
    ],
    rating: 4.9,
    reviewCount: 97,
    bookedCount: 640,
    order: 8,
  },
];

// ─── TESTIMONIALS ──────────────────────────────────────────

export const testimonials = [
  {
    _type: "testimonial",
    _id: "test-ayesha",
    name: "Ayesha Raza",
    location: "Karachi",
    rating: 5,
    tour: { _type: "reference", _ref: "tour-hunza-luxury" },
    comment: "Every detail was handled — from the private guide to the surprise apricot breakfast. Baig Tours made Hunza feel like a five-star secret. The boutique hotel in Karimabad had Rakaposhi glowing right outside our window every morning.",
    publishedAt: "2026-06-15T10:00:00Z",
    featured: true,
  },
  {
    _type: "testimonial",
    _id: "test-bilal",
    name: "Bilal Ahmed",
    location: "Lahore",
    rating: 5,
    tour: { _type: "reference", _ref: "tour-skardu-adventure" },
    comment: "Camping under the Deosai sky is something I'll never forget. The jeep drivers were pros and the whole trip felt completely safe. Sheosar Lake at sunrise was the most beautiful thing I've ever seen in Pakistan.",
    publishedAt: "2026-05-20T10:00:00Z",
    featured: true,
  },
  {
    _type: "testimonial",
    _id: "test-sara",
    name: "Sara Malik",
    location: "Islamabad",
    rating: 4.8,
    tour: { _type: "reference", _ref: "tour-swat-family" },
    comment: "Traveling with two kids is never simple, but the itinerary pace was perfect and the hotel had a playground right on the river. Our guide even arranged a surprise horse ride for the children in Kalam.",
    publishedAt: "2026-04-10T10:00:00Z",
    featured: true,
  },
  {
    _type: "testimonial",
    _id: "test-hamza",
    name: "Hamza Sheikh",
    location: "Multan",
    rating: 5,
    tour: { _type: "reference", _ref: "tour-k2-basecamp" },
    comment: "Fourteen days, four 8,000m peaks, and a support team that never once let logistics get in the way of the experience. Standing at Concordia with K2 towering above us — that's a moment I'll carry forever.",
    publishedAt: "2025-08-25T10:00:00Z",
    featured: false,
  },
  {
    _type: "testimonial",
    _id: "test-zainab",
    name: "Zainab Qureshi",
    location: "Faisalabad",
    rating: 4.9,
    tour: { _type: "reference", _ref: "tour-murree-honeymoon" },
    comment: "The candlelight dinner overlooking the valley was the highlight of our honeymoon. Booking and payment were effortless too. We're already planning our anniversary trip to Hunza with Baig Tours.",
    publishedAt: "2026-03-05T10:00:00Z",
    featured: true,
  },
  {
    _type: "testimonial",
    _id: "test-ahmed",
    name: "Ahmed Khan",
    location: "Peshawar",
    rating: 5,
    tour: { _type: "reference", _ref: "tour-naran-kaghan" },
    comment: "Saif-ul-Malook at dawn is genuinely magical — the mist lifting off the turquoise water with Makra Peak behind it. Our bonfire night with live music was the perfect end to the trip. Incredible value for money.",
    publishedAt: "2026-06-01T10:00:00Z",
    featured: false,
  },
];

// ─── GALLERY IMAGES ──────────────────────────────────────────

export const galleryImages = [
  { _type: "galleryImage", _id: "gal-01", caption: "Golden hour at Attabad Lake", location: "Hunza", likes: 482, order: 1 },
  { _type: "galleryImage", _id: "gal-02", caption: "Camp night in Deosai", location: "Skardu", likes: 391, order: 2 },
  { _type: "galleryImage", _id: "gal-03", caption: "Nanga Parbat from Fairy Meadows", location: "Fairy Meadows", likes: 567, order: 3 },
  { _type: "galleryImage", _id: "gal-04", caption: "Chairlift over Malam Jabba", location: "Swat", likes: 274, order: 4 },
  { _type: "galleryImage", _id: "gal-05", caption: "Saif-ul-Malook at dawn", location: "Naran", likes: 618, order: 5 },
  { _type: "galleryImage", _id: "gal-06", caption: "Badshahi Mosque courtyard", location: "Lahore", likes: 340, order: 6 },
  { _type: "galleryImage", _id: "gal-07", caption: "Concordia panorama", location: "K2 Base Camp", likes: 705, order: 7 },
  { _type: "galleryImage", _id: "gal-08", caption: "Cable car above the pines", location: "Murree", likes: 219, order: 8 },
  { _type: "galleryImage", _id: "gal-09", caption: "Snow-capped peaks at sunrise", location: "Gilgit-Baltistan", likes: 512, order: 9 },
  { _type: "galleryImage", _id: "gal-10", caption: "Valley road through the north", location: "Northern Pakistan", likes: 328, order: 10 },
  { _type: "galleryImage", _id: "gal-11", caption: "Trekking through the highlands", location: "Karakoram", likes: 445, order: 11 },
  { _type: "galleryImage", _id: "gal-12", caption: "Crystal clear alpine waters", location: "Skardu", likes: 389, order: 12 },
  { _type: "galleryImage", _id: "gal-13", caption: "Local village life in the mountains", location: "Hunza", likes: 276, order: 13 },
  { _type: "galleryImage", _id: "gal-14", caption: "Majestic mountain pass at sunset", location: "Deosai", likes: 503, order: 14 },
  { _type: "galleryImage", _id: "gal-15", caption: "Sunset over the Karakoram", location: "Gilgit-Baltistan", likes: 617, order: 15 },
  { _type: "galleryImage", _id: "gal-16", caption: "Trout fish lunch at Naran riverside", location: "Naran", likes: 188, order: 16 },
  { _type: "galleryImage", _id: "gal-17", caption: "Wagah Border ceremony crowd", location: "Lahore", likes: 295, order: 17 },
  { _type: "galleryImage", _id: "gal-18", caption: "Kids playing by the Swat river", location: "Swat", likes: 164, order: 18 },
  { _type: "galleryImage", _id: "gal-19", caption: "Passu Cones at golden hour", location: "Hunza", likes: 430, order: 19 },
  { _type: "galleryImage", _id: "gal-20", caption: "Stargazing from Deosai Plains", location: "Skardu", likes: 376, order: 20 },
];

// ─── FAQs ──────────────────────────────────────────────────

export const faqs = [
  {
    _type: "faq",
    _id: "faq-01",
    question: "How do I book a tour with Baig Tours?",
    answer: "You can book directly through our website by visiting the /booking page, or call us at 03079222271. Our team will confirm availability within a few hours and send you a detailed itinerary with payment options. We accept bank transfers, JazzCash, and Easypaisa.",
    category: "Booking",
    order: 1,
  },
  {
    _type: "faq",
    _id: "faq-02",
    question: "What is your cancellation and refund policy?",
    answer: "Full refund if cancelled 15+ days before departure. 50% refund for cancellations 7–14 days prior. No refund within 7 days of departure, but you can reschedule to another date within 6 months at no extra charge (subject to availability).",
    category: "Payment",
    order: 2,
  },
  {
    _type: "faq",
    _id: "faq-03",
    question: "Are your tours safe for solo travelers and women?",
    answer: "Absolutely. Safety is our top priority. All drivers are licensed, vehicles are regularly maintained, and guides are certified professionals. We regularly host solo female travelers and can arrange women-only groups on request. Our 24/7 on-trip support line is always available.",
    category: "Safety",
    order: 3,
  },
  {
    _type: "faq",
    _id: "faq-04",
    question: "What should I pack for a Northern Pakistan trek?",
    answer: "Layering is key: base layer, insulated mid-layer, and windproof shell. Broken-in trekking boots with ankle support are essential above 3,000m. Don't forget a headlamp, sunscreen SPF50+, sunglasses, and a basic first-aid kit. We send a detailed packing list after booking.",
    category: "Packing & Gear",
    order: 4,
  },
  {
    _type: "faq",
    _id: "faq-05",
    question: "Do I need a visa or permits for the Northern Areas?",
    answer: "Foreign nationals need a NOC (No Objection Certificate) for Gilgit-Baltistan and certain restricted areas. We handle all permit applications as part of the tour package. Pakistani citizens just need a valid CNIC. For K2 Base Camp treks, separate park permits are included in your package.",
    category: "Visa & Permits",
    order: 5,
  },
];

// ─── OFFERS ──────────────────────────────────────────────────

export const offers = [
  {
    _type: "offer",
    _id: "offer-monsoon",
    title: "Monsoon Madness Sale",
    slug: { current: "monsoon-madness-sale" },
    badge: "20% OFF",
    description: "Escape the city rains and head to the mountains. Get 20% off on all Hunza, Swat and Naran tours departing in July and August. Limited slots available.",
    discountPercent: 20,
    promoCode: "MONSOON20",
    validFrom: "2026-07-01T00:00:00Z",
    validUntil: "2026-08-31T23:59:59Z",
    isActive: true,
  },
  {
    _type: "offer",
    _id: "offer-early-bird",
    title: "Early Bird — K2 Base Camp 2027",
    slug: { current: "early-bird-k2-2027" },
    badge: "Early Bird",
    description: "Book your K2 Base Camp & Concordia Trek for summer 2027 before September 30 and save Rs. 25,000 per person. Includes complimentary gear rental.",
    discountPercent: 10,
    promoCode: "EARLYK2",
    validFrom: "2026-07-01T00:00:00Z",
    validUntil: "2026-09-30T23:59:59Z",
    isActive: true,
  },
  {
    _type: "offer",
    _id: "offer-family",
    title: "Family Getaway Bundle",
    slug: { current: "family-getaway-bundle" },
    badge: "FAMILY",
    description: "Book 3+ people on any Family or Honeymoon tour and the third person goes at 50% off. Includes free kids activity kit and surprise gifts. Valid all year.",
    discountPercent: 15,
    promoCode: "FAMILY15",
    validFrom: "2026-01-01T00:00:00Z",
    validUntil: "2026-12-31T23:59:59Z",
    isActive: true,
  },
];

// ─── NOTIFICATIONS ──────────────────────────────────────────

export const notifications = [
  {
    _type: "notification",
    _id: "notif-01",
    title: "New booking confirmed",
    message: "Ayesha Raza booked Hunza Valley Luxury Escape for 2 travelers, departing August 4.",
    type: "booking",
    read: false,
    createdAt: "2026-07-28T06:15:00Z",
  },
  {
    _type: "notification",
    _id: "notif-02",
    title: "New 5-star review received",
    message: "Hamza Sheikh left a 5-star review for K2 Base Camp & Concordia Trek: 'Fourteen days, four 8,000m peaks...'",
    type: "review",
    read: false,
    createdAt: "2026-07-28T05:30:00Z",
  },
  {
    _type: "notification",
    _id: "notif-03",
    title: "Contact form submission",
    message: "A traveler from Dubai asked about a custom Swat family itinerary for 6 people in September.",
    type: "contact",
    read: true,
    createdAt: "2026-07-27T14:20:00Z",
  },
];

// ─── TEAM MEMBERS ──────────────────────────────────────────

export const teamMembers = [
  {
    _type: "teamMember",
    _id: "team-abdullah",
    name: "Abdullah Baig",
    slug: { current: "abdullah-baig" },
    role: "CEO & Founder",
    bio: "Born in Gilgit, raised on the Karakoram Highway. Abdullah started Baig Tours with a single jeep and a conviction that Northern Pakistan deserves better travel experiences. Nine years and 24,000+ travelers later, that conviction drives every itinerary.",
    phone: "03079222271",
    email: "abdullah@baigtourspakistan.pk",
    order: 1,
  },
  {
    _type: "teamMember",
    _id: "team-fatima",
    name: "Fatima Noor",
    slug: { current: "fatima-noor" },
    role: "Head of Content & Marketing",
    bio: "Fatima is a travel writer turned content strategist who has been blogging about Northern Pakistan since 2019. She manages Baig Tours' blog, social media and email campaigns.",
    email: "fatima@baigtourspakistan.pk",
    order: 2,
  },
  {
    _type: "teamMember",
    _id: "team-usman",
    name: "Usman Ali",
    slug: { current: "usman-ali" },
    role: "Operations Manager",
    bio: "With 12 years in tourism logistics, Usman ensures every tour runs like clockwork — from vehicle inspections to hotel check-ins to emergency protocols on mountain roads.",
    email: "usman@baigtourspakistan.pk",
    order: 3,
  },
];

// ─── SITE SETTINGS (singleton) ──────────────────────────────

export const siteSettings = {
  _type: "siteSettings",
  _id: "siteSettings",
  companyName: "Baig Tours Pakistan",
  footerDescription:
    "Pakistan's premium travel partner for the Northern Areas — trips that make stories, planned with care from arrival to departure.",
  contact: {
    phone: "03079222271",
    email: "info@baigtourspakistan.pk",
    address: "UGF 21–22, Landmark Plaza, Jail Road, Lahore",
    workingHours: "10 AM – 10 PM",
    departureDays: "Every Monday & Thursday Night",
  },
  socialMedia: {
    facebook: "https://web.facebook.com/p/Baig-tours-Pakistan-61574927528161/?_rdc=1&_rdr#",
    instagram: "https://www.instagram.com/baigtour_pakistan_/",
    youtube: "",
    tiktok: "https://www.tiktok.com/@baigtourspakistan1",
    whatsapp: "923079222271",
  },
  googleMapsEmbed: "",
  privacyPolicySlug: { current: "privacy-policy" },
  termsSlug: { current: "terms-and-conditions" },
  about: {
    eyebrow: "Our Story",
    title: "Trips that make stories, since day one",
    description: "Baig Tours Pakistan began with a simple frustration: too many travelers were seeing the north through rushed, one-size-fits-all group tours. We started with a single jeep and a route through Hunza — today we run curated journeys across Gilgit-Baltistan, Khyber Pakhtunkhwa and Punjab, still with the same promise: every trip is planned like it's for our own family.",
  },
  founder: {
    name: "Abdullah Baig",
    role: "CEO, Baig Tours Pakistan",
    quote: "We built Baig Tours around one idea — trusted, comfortable travel that treats every guest like a returning friend, not a booking number.",
  },
  values: [
    { icon: "Shield", title: "Trusted & Safe", description: "Licensed drivers, vetted guides and 24/7 on-trip support for every group." },
    { icon: "Compass", title: "Local Expertise", description: "Every itinerary is built by guides who grew up in the valleys they lead you through." },
    { icon: "HeartHandshake", title: "Community First", description: "We hire and source locally so tourism income stays in the communities we visit." },
    { icon: "Award", title: "Premium Service", description: "From airport pickup to the final photo stop, every detail is planned in advance." },
  ],
};

// ─── HOME PAGE (singleton) ────────────────────────────────

export const homePage = {
  _type: "homePage",
  _id: "homePage",
  heroEyebrow: "Pakistan Baig Tours",
  heroHeading: "Trips that turn into the stories you tell.",
  heroSubheading: "From Hunza's golden orchards to the throne room of K2 — handcrafted Northern Pakistan journeys, guided by locals who call these valleys home.",
  stats: [
    { label: "Happy Travelers", value: 24800 },
    { label: "Curated Tours", value: 96 },
    { label: "Destinations Covered", value: 42 },
    { label: "Years of Trust", value: 9 },
  ],
  featuredToursHeading: {
    eyebrow: "Handpicked Journeys",
    title: "Featured tours our travelers keep booking",
    description: "A curated shortlist across luxury, adventure and family travel — refreshed each season by our own guides.",
  },
  destinationsHeading: {
    eyebrow: "Where To Next",
    title: "Popular destinations across the north",
    description: "Every valley has its own season, story and pace — here are the eight our travelers return to most.",
  },
  categoriesHeading: {
    eyebrow: "Travel Your Way",
    title: "Six ways to experience Pakistan",
  },
  reviewsHeading: {
    eyebrow: "Traveler Stories",
    title: "Loved by thousands of Pakistani travelers",
  },
  reelsHeading: {
    eyebrow: "Watch Before You Book",
    title: "Travel reels from the trail",
    description: "Short-form clips shot by our guides on the exact routes you'll walk.",
  },
  reels: [
    { title: "60 Seconds in Hunza" },
    { title: "Camping in Deosai" },
    { title: "Approach to Concordia" },
    { title: "Chairlift at Malam Jabba" },
    { title: "Saif-ul-Malook at Dawn" },
    { title: "A Day in Old Lahore" },
  ],
  blogsHeading: {
    eyebrow: "From The Journal",
    title: "Stories, guides & field notes",
    description: "Practical advice written by the guides who actually run these trips.",
  },
  newsletterHeading: {
    eyebrow: "Stay Inspired",
    title: "Get first access to new routes & seasonal offers",
  },
};

// ─── SEO SETTINGS (singleton) ──────────────────────────────

export const seoSettings = {
  _type: "seoSettings",
  _id: "seoSettings",
  metaTitle: "Baig Tours Pakistan | Trips That Make Stories",
  metaDescription: "Pakistan's premium travel booking platform for Hunza, Skardu, Fairy Meadows, Swat, Naran, Lahore and K2 Base Camp. Handcrafted tours, trusted local guides, effortless booking.",
  focusKeywords: "Pakistan tours, Hunza Valley tour, Skardu tour package, Northern Pakistan travel, K2 base camp trek, Baig Tours Pakistan",
  canonicalDomain: "https://www.baigtourspakistan.pk",
  siteName: "Baig Tours Pakistan",
  locale: "en_PK",
};

// ─── BLOG POSTS ──────────────────────────────────────────────

export const blogPosts = [
  {
    _type: "blogPost",
    _id: "blog-hunza-season",
    title: "The Best Time to Visit Hunza Valley (Season by Season)",
    slug: { current: "best-time-to-visit-hunza-valley" },
    excerpt: "From cherry blossoms in spring to golden autumn orchards — here's how to pick the right month for your Hunza trip.",
    author: "Abdullah Baig",
    category: "Travel Guides",
    tags: ["Hunza", "Seasons", "Planning"],
    readTime: "6 min read",
    publishedAt: "2026-07-12T10:00:00Z",
  },
  {
    _type: "blogPost",
    _id: "blog-packing",
    title: "The Complete Packing List for a Northern Pakistan Trek",
    slug: { current: "packing-list-northern-pakistan-trek" },
    excerpt: "What actually earns space in your bag for a multi-day trek through Gilgit-Baltistan — and what to leave behind.",
    author: "Fatima Noor",
    category: "Trekking",
    tags: ["Packing", "Trekking", "Gear"],
    readTime: "5 min read",
    publishedAt: "2026-06-28T10:00:00Z",
  },
  {
    _type: "blogPost",
    _id: "blog-lakes",
    title: "5 Hidden Lakes of Gilgit-Baltistan Most Tourists Miss",
    slug: { current: "hidden-lakes-of-gilgit-baltistan" },
    excerpt: "Beyond Saif-ul-Malook — the quieter alpine lakes worth the extra hour of driving.",
    author: "Abdullah Baig",
    category: "Destinations",
    tags: ["Lakes", "Gilgit-Baltistan", "Hidden Gems"],
    readTime: "7 min read",
    publishedAt: "2026-06-03T10:00:00Z",
  },
  {
    _type: "blogPost",
    _id: "blog-responsible",
    title: "How We Practice Responsible Tourism in the Northern Areas",
    slug: { current: "responsible-tourism-northern-areas" },
    excerpt: "Our approach to protecting the trails, villages and glaciers that make Northern Pakistan worth visiting.",
    author: "Abdullah Baig",
    category: "Sustainability",
    tags: ["Responsible Travel", "Community"],
    readTime: "4 min read",
    publishedAt: "2026-05-20T10:00:00Z",
  },
];

// ─── SITE NOTIFICATIONS (Homepage Banner) ──────────────────

export const siteNotifications = [
  {
    _type: "siteNotification",
    _id: "site-notif-01",
    title: "Summer Sale",
    message: "Book any Northern Pakistan tour and get 15% off — offer valid until August 15.",
    variant: "promo",
    isActive: true,
    scheduledAt: "2026-07-01T00:00:00Z",
    expiresAt: "2026-08-16T00:00:00Z",
    link: "/tours",
    linkText: "View Tours",
  },
  {
    _type: "siteNotification",
    _id: "site-notif-02",
    title: "New Blog Post",
    message: "Read our latest guide: Hidden Lakes of Gilgit-Baltistan — alpine gems worth the extra hour of driving.",
    variant: "info",
    isActive: false,
    scheduledAt: "2026-07-03T00:00:00Z",
    expiresAt: "2026-07-31T00:00:00Z",
    link: "/blog",
    linkText: "Read Blog",
  },
  {
    _type: "siteNotification",
    _id: "site-notif-03",
    title: "Independence Day Announcement",
    message: "Special August 14th cultural tour of Lahore — limited spots available.",
    variant: "announcement",
    isActive: true,
    scheduledAt: "2026-08-01T00:00:00Z",
    expiresAt: "2026-08-15T00:00:00Z",
    link: "/tours",
    linkText: "Book Now",
  },
];
